apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-notifier-deployment
  labels:
    app: deploy-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-notifier
  template:
    metadata:
      labels:
        app: deploy-notifier
    spec:
      serviceAccountName: list-watch-sa
      containers:
        - name: deploy-notifier-container
          image: ghcr.io/ponty96/deploy-notifier:9b4e44a-local-build
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/deploy-notifier-config.yaml
              # readOnly: true
              subPath: deploy-notifier-config.yaml
          startupProbe:
            httpGet:
              path: /health-check
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health-check
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      volumes:
        - name: config-volume
          configMap:
            name: deploy-notifier-config
