apiVersion: v1
kind: ServiceAccount
metadata:
  name: list-watch-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-watch-role
rules:
  - apiGroups: [""]
    resources: ["events", "pods"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-watch-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-watch-role
subjects:
  - kind: ServiceAccount
    name: list-watch-sa
    namespace: default
